name: aay_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  device_info: ^2.0.3
  provider: ^5.0.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/HomePage_img.png
    - assets/Book_image.png
    - assets/Coffee_image.png
    - assets/StudyPage.png
    - assets/Tasks_icon.png
    - assets/TasksPage.png
    - assets/PlacesPage.png
    - assets/account_circle_icon.png
    - assets/info_icon.png
    - assets/settings_icon.png
    - assets/MusicPage.png
    - assets/SettingsPage.png
    - assets/overlays/Settings_info_overlay.png
    - assets/overlays/Study_info_overlay.png
    - assets/overlays/Places_info_overlay.png
    - assets/overlays/Music_info_overlay.png
    - assets/overlays/Empty_overlay.png
  uses-material-design: true
